### ISSUE TITLE
无码海报能否不要裁切？

### ISSUE THREAD

**Issue by LeeHK1989** [mdc-ng/mdc-ng#2]
无码的海报大部分是横向的，在PLEX里面显示会被裁切，只取到一小部分竖向显示，几乎没法看。
我之前用过一款刮削软件的方法是，在上下加入黑边。使得海报能显示完整，请问咱这个软件能否也考虑这个方法呢

**Comment by mdc-ng** [comment]
https://github.com/mdc-ng/mdc-ng/releases/tag/v0.45.0
