### ISSUE TITLE
0.45 无法下载

### ISSUE THREAD

**Issue by simple-life0** [mdc-ng/mdc-ng#3]
![IMAGE 2024-06-21 18:28:05](https://github.com/mdc-ng/mdc-ng/assets/57739839/5c63d1e7-d0e7-44a0-a10f-ee018d95b5aa)
科学了 数据能访问到了 没办法下载 这个还是个人网络问题吗?

**Comment by mdc-ng** [comment]
没开启缩略图下载但是开启了裁剪。开启缩略图可以解决，下个版本优化错误提示

**Comment by mdc-ng** [comment]
0.46.2已修复
